name: "AIS-catcher Control"
version: "1.0.0"
slug: "ais_catcher_control"
description: "Home Assistant Add-on to run AIS-catcher Control."
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
ports:
  8110/tcp: 8110
schema: {}
