slug: ais_catcher_control
name: "AIS-catcher Control"
description: "AIS-catcher Control for managing AIS-catcher services."
url: https://github.com/CzarofAK/homeassistant-addons/
image: ghcr.io/czarofak/homeassistant-ais_catcher_control-{arch}
version: "1.0.0"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
usb: true
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8100
ports:
  8110/tcp: 8110
  8100/tcp: 8100
panel_icon: mdi:ferry
panel_title: AIS Catcher
options:
  HTML_SITE_LAT: HOMEASSISTANT_LATITUDE
  HTML_SITE_LON: HOMEASSISTANT_LONGITUDE
schema:
  HTML_SITE_LAT: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LATITUDE)?
  HTML_SITE_LON: match([+-]?(([1-9][0-9]*)|(0))([.,][0-9]+)?|HOMEASSISTANT_LONGITUDE)?
