name: AIS Catcher Control
version: "1.0.0"
slug: ais_catcher_control
description: AIS catcher control addon.
arch:
  - aarch64
  - amd64
  - armhf
options:
  device: /dev/ttyUSB0
  gain: 42.1
  lat: 0.0
  lon: 0.0
  web_port: 8080
schema:
  device: str
  gain: float
  lat: float
  lon: float
  web_port: int
ports:
  8080/tcp: 8080
