slug: ais_catcher_control
name: "AIS-catcher Control"
description: "AIS-catcher Control for managing AIS-catcher services."
version: "1.0.0"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
boot: "auto"
usb: true
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8100
ports:
  8110/tcp: 8110
  8100/tcp: 8100
panel_icon: mdi:ferry
panel_title: AIS Catcher
options: {}
schema: {}
